# audioBlastIngest
The ingest service is responsible for bringing data about recordings, deployments, annotation, taxa and traits into the audioBlast system. Data sources are specified as modules within the audioBlast API, which give details of each data source and the processing that is expected to be performed by the ingest process. The ingest process itself is managed on audioBlast infrastructure by the audioBlastIngest package. This package obtains data from the sources specified in the API modules, performs and requested transformations, and loads the data into the audioBlast database.

Note: The database generates analysis tasks using triggers as data is inserted or updated, however the analyses are performed by a separate processes to the ingest.

Updates are handled periodically (generally nightly) by the ingest server. Creating an ingest task is a simple three step process.

1. Third party publishes data online.

2. audioBlast team work with third party to create an API module to map the published data on to audioBlast data structures.

3. The audioBlastIngest package handles the import of the data.

## Source modules

### Fields

### Mapping columns

#### Optional processing done by audioBlast

##### Specifying processors

###### SourceR: Automatically prepend a source column

###### date2dateAnTime(): Date and time mapping

You can map datetime fields to Date and use the date2dateAndTime() processor to split them into separate date and time fields.


